# Generated by Django 3.2.2 on 2021-05-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='occupation',
            field=models.CharField(choices=[('p', 'plumber'), ('w', 'welder'), ('m', 'mechanic'), ('d', 'developer')], default='not sepcified', max_length=20),
        ),
    ]
