# Generated by Django 3.2.2 on 2021-05-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_person_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='not specified', max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='occupation',
            field=models.CharField(choices=[('p', 'plumber'), ('d', 'developer'), ('m', 'mechanic'), ('w', 'welder')], default='not specified', max_length=20),
        ),
    ]
