# Generated by Django 3.2.2 on 2021-05-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210511_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='occupation',
            field=models.CharField(choices=[('w', 'welder'), ('m', 'mechanic'), ('p', 'plumber'), ('d', 'developer')], default='not specified', max_length=20),
        ),
    ]
