# Generated by Django 3.2.2 on 2021-05-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_person_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='occupation',
            field=models.CharField(choices=[('m', 'mechanic'), ('w', 'welder'), ('d', 'developer'), ('p', 'plumber')], default='not specified', max_length=20),
        ),
    ]
